version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolistdb
      MYSQL_USER: esmt
      MYSQL_PASSWORD: passer
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"

  adminer:
    image: adminer
    container_name: adminer-ui
    restart: always
    ports:
      - "8080:8080"

  server:
    build:
      context: ../server
      dockerfile: Dockerfile
    container_name: server-app
    restart: always
    ports:
      - "4040:4040"
    environment:
      DB_HOST: mysql
      DB_USER: esmt
      DB_PASSWORD: passer
      DB_NAME: todolistdb
    depends_on:
      - mysql

  client:
    build:
      context: ../client
      dockerfile: Dockerfile
    container_name: client-app
    restart: always
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  mysql-data :
