services:
  mysql:
    image: mysql:8.0
    container_name: mysql-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolistdb
      MYSQL_USER: esmt
      MYSQL_PASSWORD: passer
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    container_name: adminer-ui
    restart: always
    ports:
      - "8080:8080"

volumes:
  mysql-data:
