#FROM node:22.16.0

# Dossier de travail dans le conteneur
#WORKDIR /app

# Copier les fichiers nécessaires
#COPY . .

# Installer les dépendances
#RUN npm install

# Exposer le port utilisé dans serveur.js
#EXPOSE 3000

# Démarrer l'application
#CMD ["node", "serveur.js"]
